capstoneapp/urls.py
from django.urls import path
from . import views

app_name = 'capstoneapp'
urlpatterns = [
path('index/', views.index, name='index'),
path('census/', views.census, name='census'),
path('profiles/', views.profiles, name='profiles'),
path('about/', views.about, name='about'),
path('vote/', views.vote, name='vote'),
path('base/', views.base, name='base'),
path('charts/', views.charts, name='charts'),
path('chartsmale/', views.chartsmale, name='chartsmale'),
path('totalvotes/', views.totalvotes, name='totalvotes'),
path('trendline/', views.trendline, name='trendline'),
path('about/', views.about, name='about'),
path('base/', views.base, name='base'),

]

capstoneproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('capstoneapp.urls'))

]  +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # adding route to access media files
                                                                     # this gives user ability to access the files statically 
                                                                     # there is built in access restriction, so anyone with a valid link can view and download file

capstoneapp/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length = 200)
    last_name = models.CharField(max_length = 200)
    state = models.CharField(max_length = 20)
    political_party = models.CharField(max_length=20)
    my_image = models.ImageField(upload_to='images/', null=True, blank=True)
    contact_url = models.CharField(max_length = 200, null=True, blank=True)
    next_election = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class DataSet(models.Model):
    state = models.CharField(max_length = 30) 
    population_total = models.IntegerField(null=True, blank=True) 
    registered_voters_total = models.IntegerField(null=True, blank=True) 
    registered_voters_percent = models.FloatField(null=True, blank=True) 
    total_voters = models.IntegerField(null=True, blank=True)
    total_voters_percent = models.FloatField(null=True, blank=True)
    males_population_total = models.IntegerField(null=True, blank=True)
    males_registered_total = models.IntegerField(null=True, blank=True)
    males_registered_percent = models.FloatField(null=True, blank=True)
    males_voted_total = models.IntegerField(null=True, blank=True)
    males_voted_percent = models.FloatField(null=True, blank=True)
    females_population_total = models.IntegerField(null=True, blank=True)
    females_registered_total = models.IntegerField(null=True, blank=True)
    females_registered_percent = models.FloatField(null=True, blank=True)
    females_voted_total = models.IntegerField(null=True, blank=True)
    females_voted_percent = models.FloatField(null=True, blank=True)
    white_population_total = models.IntegerField(null=True, blank=True)
    white_registered_total = models.IntegerField(null=True, blank=True)
    white_registered_percent = models.FloatField(null=True, blank=True)
    white_voted_total = models.IntegerField(null=True, blank=True)
    white_voted_percent = models.FloatField(null=True, blank=True)
    black_population_total = models.IntegerField(null=True, blank=True)
    black_registered_total = models.IntegerField(null=True, blank=True)
    black_registered_percent = models.FloatField(null=True, blank=True)
    black_voted_total = models.IntegerField(null=True, blank=True)
    black_voted_percent = models.FloatField(null=True, blank=True)
    asian_population_total = models.IntegerField(null=True, blank=True)
    asian_registered_total = models.IntegerField(null=True, blank=True)
    asian_registered_percent = models.FloatField(null=True, blank=True)
    asian_voted_total = models.IntegerField(null=True, blank=True)
    asian_voted_percent = models.FloatField(null=True, blank=True)
    hispanic_population_total = models.IntegerField(null=True, blank=True)
    hispanic_registered_total = models.IntegerField(null=True, blank=True)
    hispanic_registered_percent = models.FloatField(null=True, blank=True)
    hispanic_voted_total = models.IntegerField(null=True, blank=True)
    hispanic_voted_percent = models.FloatField(null=True, blank=True)
    age_18to24_population_total = models.IntegerField(null=True, blank=True)
    age_18to24_registered_total = models.IntegerField(null=True, blank=True)
    age_18to24_registered_percent = models.FloatField(null=True, blank=True)
    age_18to24_voted_total = models.IntegerField(null=True, blank=True)
    age_18to24_voted_percent = models.FloatField(null=True, blank=True)
    age_25to34_population_total = models.IntegerField(null=True, blank=True)
    age_25to34_registered_total = models.IntegerField(null=True, blank=True)
    age_25to34_registered_percent = models.FloatField(null=True, blank=True)
    age_25to34_voted_total = models.IntegerField(null=True, blank=True)
    age_25to34_voted_percent = models.FloatField(null=True, blank=True)
    age_35to44_population_total = models.IntegerField(null=True, blank=True)
    age_35to44_registered_total = models.IntegerField(null=True, blank=True)
    age_35to44_registered_percent = models.FloatField(null=True, blank=True)
    age_35to44_voted_total = models.IntegerField(null=True, blank=True)
    age_35to44_voted_percent = models.FloatField(null=True, blank=True)
    age_45to64_population_total = models.IntegerField(null=True, blank=True)
    age_45to64_registered_total = models.IntegerField(null=True, blank=True)
    age_45to64_registered_percent = models.FloatField(null=True, blank=True)
    age_45to64_voted_total = models.IntegerField(null=True, blank=True)
    age_45to64_voted_percent = models.FloatField(null=True, blank=True)
    age_65plus_population_total = models.IntegerField(null=True, blank=True)
    age_65plus_registered_total = models.IntegerField(null=True, blank=True)
    age_65plus_registered_percent = models.FloatField(null=True, blank=True)
    age_65plus_voted_total = models.IntegerField(null=True, blank=True)
    age_65plus_voted_percent = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.state






# class DataSet(models.Model):
#     state = models.CharField(max_length = 30) 
#     population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     registered_voters_total = models.CharField(null=True, blank=True, max_length = 20) 
#     registered_voters_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     total_voters = models.CharField(null=True, blank=True, max_length = 20) 
#     total_voters_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     males_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     males_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     males_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     males_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     males_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     females_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     females_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     females_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     females_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     females_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     white_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     white_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     white_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     white_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     white_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     black_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     black_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     black_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     black_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     black_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     asian_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     asian_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     asian_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     asian_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     asian_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     hispanic_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     hispanic_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     hispanic_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     hispanic_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     hispanic_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     age_18to24_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_18to24_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_18to24_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     age_18to24_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_18to24_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     age_25to34_population_total =models.CharField(null=True, blank=True, max_length = 20) 
#     age_25to34_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_25to34_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     age_25to34_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_25to34_voted_percent = models.FloatField(null=True, blank=True)
#     age_35to44_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_35to44_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_35to44_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     age_35to44_voted_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_35to44_voted_percent = models.CharField(null=True, blank=True, max_length = 20) 
#     age_45to64_population_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_45to64_registered_total = models.CharField(null=True, blank=True, max_length = 20) 
#     age_45to64_registered_percent = models.CharField(null=True, blank=True, max_length = 20) 

capstoneapp/views.py
from django.shortcuts import HttpResponse, render, reverse
from .models import DataSet, Profile
from django.utils import timezone 

#Purpose of a view is to connect models and templates.  
#Supports taking content (models saved in database) and display in template
#In views, decide what model I want displayed in template
#Take the models I want to display and pass them to a template 

#localhost:8000/index
def index(request):
    return HttpResponse('Page reserved for the Map!')

#localhost:8000/census
def census(request):
    #return HttpResponse('Page reserved for census data ')
    data = DataSet.objects.all()
    context = {
        "data":data #variable in the loop statement needs to match this, in this case needs to match "data"
    }
    return render(request, 'capstoneapp/census.html', context) 

#localhost:8000/profiles
def profiles(request):
    #return HttpResponse('Page reserved for senators profiles')
    profiles = Profile.objects.order_by('political_party', 'state')
    context = {}

    democrats = Profile.objects.filter(political_party='D').order_by('state')
    context = {}

    republicans = Profile.objects.filter(political_party='R').order_by('state')
    context = {}

    independents = Profile.objects.filter(political_party='ID').order_by('state')
    context = {
                "profiles" : profiles,
                "independents" : independents,
                "democrats" : democrats,
                "republicans" : republicans,}


    return render(request, 'capstoneapp/profiles.html', context) 

#localhost:8000/about
def about(request):
    return HttpResponse('Page reserved for historical summary of US voting..chart showing voter participation from 1900 to present  ')

#localhost:8000/vote
def vote(request):
    return HttpResponse('Page reserved for voter registration form')

#localhost:8000/base
def base(request):
    #return HttpResponse('THIS IS THE BASE PAGE')
    return render(request, 'capstoneapp/base.html') 

#localhost:8000/charts
def charts(request):
    #return HttpResponse('THIS IS MY D3 PAGE')
    return render(request, 'capstoneapp/charts.html')

#localhost:8000/chartsmale
def chartsmale(request):
    #return HttpResponse('HISTORICAL ')
    return render(request, 'capstoneapp/chartsmale.html')

#localhost:8000/totalvotes
def totalvotes(request):
    #return HttpResponse('THIS IS TOTAL US VOTES')
    return render(request, 'capstoneapp/totalusvotes.html')

#localhost:8000/trendline
def trendline(request):
    #return HttpResponse('HISTORICAL ')
    return render(request, 'capstoneapp/trendline.html')


#localhost:8000/base
def about(request):
    #return HttpResponse('ABOUT PAGE ')
    return render(request, 'capstoneapp/about.html')

capstoneapp/templates/capstoneapp/base copy.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>CAPTSTONE TEMPLATE</title>
    <!-- Bootstrap File-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    
    <style type="text/css">
        .home-inner {
            background-image: url("{% static 'images\ballotbox.jpg' %}");
        }


    </style>
     
     
   


</head>
<!--  Bootstrap Scroll Spy - When scorlling thru websites, sections will highlight in Navigation Bar -->
<!--  data target = #navbarResponsive is the link to id that will give the navigation -->
<!--  Next step is to identify id for each section that user will scroll thru, ie Home, About, Sign Up-->
<body data-spy="scroll" data-target="#navbarResponsive">

<!--Start Home Section. ID for Bootstrap Scroll Spy. 1st Id for the home navigation link-->
<div id="home">

<!-- Start Navigation -->
<!--Navigation navbar is html tag for navigation bar, navbar-expand-md is for responsiveness, navbar-dark is color for naviation links, 
    bg-dark will give navigation dark background, fixed-top will force navigation bar to stay fixed at top while scorlling the site.
    This will return a solid line across the screen-->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#" </a> <!--display logo inside navbar-->
    
    <!-- Creates collapsable navbar toggler button and applies scroll spy via data-target navbarResponsive -->
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span> <!-- creates hamburger button inside the collapsable navbar toggler button-->
    </button>

    <!-- Creating Collapsable Navigation Menu on left hand side.  -->
    <div class="collapse navbar-collapse" id="navbarResponsive">

       <!-- Creating unordered list items and navigation links--> 
        <ul class="navbar-nav ml-auto">  <!-- ml auto moves to left-->
            <li class="nav-item">
                <a class="nav-link" href="#home">Home</a> <!--linking to the home id-->
            </li>
             <li class="nav-item">
                <a class="nav-link" href="#about">About</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="#stats">Register</a>
            </li>
             
        </ul>
    </div>    
</nav>
<!-- End Navigation-->

<!--Start Fixed Image Landing Page. Refers to fixed css file. Used for mobile responsiveness. Also needed to put caption section on landing page  -->
<div class="landing">
    <div class="home-wrap">
        <div class="home-inner">
        </div>
    </div>
</div> 
<!-- Creates comments that will sit on top of the landing page. -->
<div class="caption text-center">
    <h1>Welcome To Voting 2020</h1>
    <h3> Register To Vote! </h3>
    <a class="btn btn-outline-light btn-lg" href="#about">Get Started</a>
</div>
<!-- End Landing Page-->

</div>
<!-- End Home Section -->

<!--Start about Section  ID for Bootstrap Scroll Spy. 2nd Id for the home navigation link-->
<div id="about" class="offset"> <!--offset accounts for spacing between sections-->

<!--Text that will appear in section after the Home Page -->
    <div class="col-12 narrow text-center"> <!-- col-12 add space between section, narrow pads on sides-->
        <h1> Become an engaged citizien and vote in the 2020 election</h1>
        <p class="lead"> Contact your local senator </p>
    </div>

</div>
<!-- End about Section -->

<!--Start stats Section ID for Bootstrap Scroll Spy. 3rd Id for the home navigation link-->
<div id="stats" class="offset">

<!-- Start Jumbotron-->
<div class="jumbotron">
<div class="narrow text-center"> <!-- narrow brings columns to 75% of the page-->

<!-- Within jumbotron narrow, creating a column length of 12 and within the column putting a heading with stats text -->
    <div class="col-12">
        <h3 class="heading">Understanding The Voting Process</h3>
        <div class="heading-underline"></div>
    </div>

        <!-- Begin Row. Will have 3 sections each 4 columns -->
        <div class="row text-center">

        <div class="col-12">
                <h3 class="heading">.</h3>
                <div class="heading-underline"></div>
        </div>        

            <div class="col-md-4"> <!-- creating 3 columns-->
                <div class="feature">
                    <i class="fas fa-person-booth fa-4x" data-fa-transform="shrink-3 up-5"></i>> <!--icon for circle, 4x original size i stands for icon-->
                    <h3>Common Voting And Election Terms </h3>
                    <p>Terms </p>
                </div>
            </div>

            <div class="col-md-4"> <!-- creating 3 columns-->
                <div class="feature">
                    <i class="fas fa-vote-yea fa-4x" data-fa-transform="shrink-4.5 up-4.5"></i>> <!--icon for circle, 4x original size i stands for icon-->
                    <h3>How To Register To Vote</h3>
                    <p>Register</p>
                </div>
            </div>

            <div class="col-md-4"> <!-- creating 3 columns-->
                <div class="feature">
                    <i class="fab fa-wpforms fa-4x" data-fa-transform="shrink-4 up-5"></i>> <!--icon for circle, 4x original size i stands for icon-->
                    <h3>Presidental Election Process</h3>
                    <p>Process</p> 
                </div>
            </div>
    
        </div> <!-- End Row-->

</div> <!-- End Narrow-->
</div> <!-- End Jumbotron-->

<!-- End stats Section -->


<!--Start Contact Section ID for Bootstrap Scroll Spy. 6th Id for the home navigation link-->
<div id="contact" class="offset">

<footer>
<div class="row justify-content-center">
    <div class="col-md-5 text-center">
    <p>Connect via social media</p>
    <strong>Contact Info</strong>
    <p>(555) 555.5555<br>email@email.com</p>
    <a href="" target="_blank"><i class="fab fa-facebook-square"></i></a>
    <a href="" target="_blank"><i class="fab fa-twitter-square"></i></a>
    <a href="" target="_blank"><i class="fab fa-instagram"></i></a>
    </div>    
</div>
</footer>
</div>
<!-- End Contact Section -->

<!--- Bootstrap Files -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!--- Fontawesome Files -->
<script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>
<!--- End of Script Source Files -->
{% block content%}
{% endblock%}
</body>

capstoneapp/templates/capstoneapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>CAPTSTONE TEMPLATE</title>
    <!-- Bootstrap File-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
       
</head>

<body >


<!-- Start Navigation -->
    <ul class="navbar nav nav-pills justify-content-end"> <!-- to keep navbar "stuck", navbar referenced in css file -->
        <li class="nav-item">
            <a class="nav-link active" href={% url 'capstoneapp:about' %}>Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'capstoneapp:profiles' %}">Contact Your Senator</a> <!-- url acts as a reverse lookup. name of the app, followed by name of the view -->
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'capstoneapp:census' %}">Census Data</a> <!-- url appname:viewname-->
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Register To Vote</a>
        </li>
    </ul>
<!-- End Navigation-->

<!--Start about Section  ID for Bootstrap Scroll Spy. 2nd Id for the home navigation link-->
<div id="about" > </div>

<!--Start about Section  ID for Bootstrap Scroll Spy. 2nd Id for the home navigation link-->
<div id="profile"> </div>

<!--Start about Section  ID for Bootstrap Scroll Spy. 2nd Id for the home navigation link-->
<div id="data"> </div>

<!--Start about Section  ID for Bootstrap Scroll Spy. 2nd Id for the home navigation link-->
<div id="vote" > </div>





<!--- Bootstrap Files -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!--- Fontawesome Files -->
<script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>
<!--- End of Script Source Files -->
{% block content%}
{% endblock%}
</body>

capstoneapp/templates/capstoneapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1></h1>
</body>
</html>